apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-bionic-mk1
    kubevirt.io/domain: bionic-mk1
  name: vmi-bionic-mk1
  namespace: zuul-ci

spec:
  #nodeSelector:
  #  kubevirt-bm: "true"
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 8192M
        cpu: "4"
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: localhost:5000/kube-stack/ubuntu-bionic-minikube:072019
    name: containerdisk
