apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-data
  labels:
    kubernetes.io/cluster-service: "true"

spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/registry-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-stack-k8s-node-5
